config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get '/about-us', to: 'pages#about'
  get '/support', to: 'pages#support'
  get '/locations', to: 'pages#locations'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :recipes

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/recipe.rb
class Recipe < ApplicationRecord
    validates :name, presence: true
    validates :description, presence: true, length: { minimum: 5, maximum: 1000 }

    belongs_to :chef
    validates :chef_id, presence: true
    default_scope -> { order(updated_at: :desc)}
    has_many :recipe_ingredients
    has_many :ingredients, through: :recipe_ingredients
    has_many :comments, dependent: :destroy
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update, :destroy]
  before_action :require_user, except: [:index, :show]
  before_action :require_same_user, only: [:edit, :update, :destroy]

  def index
    @recipes = Recipe.paginate(page: params[:page], per_page: 6)
  end

  def show
    @comments = @recipe.comments.paginate(page: params[:page], per_page: 5)
  end

  def new
    @recipe = Recipe.new
  end

  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.chef = current_chef
    if @recipe.save
      flash[:success] = "Recipe was created successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'new'
    end
  end

  def edit
  end

  def update
    if @recipe.update(recipe_params)
      flash[:success] = "Recipe was updated successfully!"
      redirect_to recipe_path(@recipe)
    else
      render 'edit'
    end
  end

  def destroy
    @recipe.destroy
    flash[:success] = "Recipe deleted successfully!"
    redirect_to recipes_path
  end

  private

  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  def recipe_params
    params.require(:recipe).permit(:name, :description, ingredient_ids: [])
  end

  def require_same_user
    if current_chef != @recipe.chef && !current_chef.admin?
      flash[:danger] = "You can only edit or delete your own recipes"
      redirect_to recipes_path
    end
  end
end

app/views/recipes/_form.html.erb
<%= render 'shared/application_errors', obj: @recipe %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@recipe, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of recipe", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :description %>
        </div>
        <div class="col-md-8">
          <%= f.text_area :description, rows: 10, class: "form-control", placeholder: "Enter steps to create recipe" %>
        </div>
      </div>
      <div class="form-group">
        <div class="row">
          <div class="col-md-offset-2 col-md-8">
            <%= f.collection_check_boxes :ingredient_ids, Ingredient.all, :id, :name do |ing| %>
              <% ing.label(class: "checkbox-inline input_checkbox") {ing.check_box(class: "checkbox") + " " + ing.text} %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit class: "btn btn-primary btn-large btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-4">
      [ <%= link_to "Cancel request and return to recipes listing", recipes_path %> ]
    </div>
  </div>
</div>

app/views/recipes/_recipe.html.erb
<% obj.each do |recipe| %>
  <div class="card">
    <div class="row">
      <div class="col-md-2">
      </div>
      <div class="chef_info col-md-1">
        <%= gravatar_for(recipe.chef, size: 120) %>
      </div>
      <div class="col-md-7">
        <div class="card-body">
          <h5><%= link_to recipe.name, recipe_path(recipe) %></h5>
          <p><%= truncate(recipe.description, length: 150) %></p>
          <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago by Chef <%= recipe.chef.chefname.capitalize %> </small></span></p>
          <div class="btn-group">
            <%= link_to "View", recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
            <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
            <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
            <%= link_to "Delete", recipe_path(recipe), method: :delete,
            data: { confirm: "Are you sure you want to delete this recipe?" },
            type: "button",
            class: "btn btn-sm btn-outline-secondary"%>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col-md-2">
      </div>
    </div>
  </div>
<% end %>

app/views/recipes/_recipex.html.erb
<div class="container py-5">
  <div class="row">
    <% obj.each do |recipe| %>
    <div class="col-md-4">
      <div class="card mb-4 box-shadow">
        <%= image_tag "iph_200x200.svg", class: 'card-img-top', alt: "Card image cap" %>
        <div class="card-body">
          <h3 class="mb-0"><%= link_to recipe.name, recipe_path(recipe) %></h3>
          <p class="card-text"><%= truncate(recipe.description, length: 75) %></p>
          <% if recipe.ingredients.any? %>
            <p>Ingredients: <%= render recipe.ingredients %></p>
          <% end %>
          <div class="d-flex justify-content-between align-items-center">
            <div class="btn-group">
                <%= link_to "View", recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
              <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
                <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
                <%= link_to "Delete", recipe_path(recipe), method: :delete,
                                                            data: { confirm: "Are you sure you want to delete this recipe?" },
                                                            type: "button",
                                                            class: "btn btn-sm btn-outline-secondary"%>
              <% end %>
            </div>
            <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small></span></p>
          </div>
        </div>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/recipes/edit.html.erb
<div class="container py-5 bg-light">
  <%= render 'shared/page_title', title: 'Edit an Existing Recipe' %>
  <%= render 'form' %>
</div>

app/views/recipes/index.html.erb
<div class="container py-5 bg-light">
  <%= render 'shared/page_title', title: 'Recipes Listing' %>
  <div class="row">
    <div class="container">
      <%= will_paginate class: "text-center" %>
      <%= render 'recipe', obj: @recipes %>
      <%= will_paginate class: "text-center" %>
    </div>
  </div>
</div>

<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
      <% @recipes.each do |recipe| %>
      <div class="col-md-4">
        <div class="card mb-4 box-shadow">
          <%= image_tag "iph_200x200.svg", class: 'card-img-top', alt: "Card image cap" %>
          <div class="card-body">
            <h3 class="mb-0"><%= link_to recipe.name, recipe_path(recipe) %></h3>
            <p class="card-text"><%= truncate(recipe.description, length: 75) %></p>
            <div class="d-flex justify-content-between align-items-center">
              <div class="btn-group">
                  <%= link_to "View", recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
                <% if logged_in? && (current_chef == recipe.chef || current_chef.admin?) %>
                  <%= link_to "Edit", edit_recipe_path(recipe), class: "btn btn-sm btn-outline-secondary", type: "button" %>
                  <%= link_to "Delete", recipe_path(recipe), method: :delete,
                                                              data: { confirm: "Are you sure you want to delete this recipe?" },
                                                              type: "button",
                                                              class: "btn btn-sm btn-outline-secondary"%>
                <% end %>
              </div>
              <p><span class="quiet"><small>Created <%= time_ago_in_words(recipe.created_at) %> ago</small></span></p>
            </div>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/recipes/new.html.erb
<div class="container py-5 bg-light">
  <%= render 'shared/page_title', title: 'Create a New Recipe' %>
  <%= render 'form' %>
</div>

app/views/recipes/show.html.erb
<div class="container py-5 bg-light">
  <%= render 'shared/page_title', title: @recipe.name %>

  <div class="row">
    <div class="col-md-1">
    </div>
    <div class="col-md-10">
      <h4 class="center description"><strong>Steps: </strong></h4>
      <hr />
      <p class="lead"><%= simple_format(@recipe.description) %></p>
      <hr />

      <% if @recipe.ingredients.any? %>
        <p>Ingredients: <%= render @recipe.ingredients %></p>
      <% end %>

      <div class="recipe-actions">
        <% if logged_in? && (current_chef == @recipe.chef || current_chef.admin?) %>
          <%= link_to "Edit", edit_recipe_path(@recipe), class: "btn btn-xs btn-outline-success" %>
          <%= link_to "Delete", recipe_path(@recipe), method: :delete,
                                                      data: { confirm: "Are you sure you want to delete this recipe?" },
                                                      class: "btn btn-xs btn-outline-danger"
          %>
        <% end %>
        <%= link_to "Return to recipes listing", recipes_path, class: "btn btn-xs btn-outline-primary" %>
      </div>

      <div align="right">
        <p class="center">Recipe by: </p>
        <p><%= link_to gravatar_for(@recipe.chef), chef_path(@recipe.chef) %></p>
        <p><span><small>Chef <%= @recipe.chef.chefname.capitalize %> </small></span></p>
      </div>

      <div align='right'><small>Posted <%= time_ago_in_words(@recipe.created_at) %> ago</small></div>
    </div>
  </div>

  <% if @recipe.comments.any? %>
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h4 class="center description"><strong>Review Comments: </strong></h4>
        <hr />
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
      </div>
    </div>
  <% else %>
    <div class="row">
      <div class="col-md-1">
      </div>
      <div class="col-md-8 col-md-offset-2">
        <h4 class="center description">
          <strong>No Comments Yet!</strong>
        </h4>
      </div>
    </div>
  <% end %>

</div>