config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get '/about-us', to: 'pages#about'
  get '/support', to: 'pages#support'
  get '/locations', to: 'pages#locations'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :recipes

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/views/shared/_application_errors.html.erb
<% if obj.errors.any? %>
  <div class="row justify-content-center">
    <div class="col-md-10">
      <div class="card text-white bg-danger mb-3">
        <div class="card-header">
          <h5 class="card-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this <%= obj.class %> from being saved:
          </h5>
        </div>
        <div class="card-body">
          <p class="card-text">
            <ul>
              <% obj.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
              <% end %>
            </ul>
          </p>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_application_footer.html.erb
<footer class="container py-5">
  <div class="row pl-3">
    <div class="col-12 col-md">
      <small class="d-block text-muted pb-3"><%= copyright_generator %></small>
    </div>
    <div class="col-6 col-md offset-md-4">
      <h5>About</h5>
      <ul class="list-unstyled text-small">
        <li><%= link_to "Team", about_us_path, class:"text-muted" %></li>
        <li><%= link_to "Locations", locations_path, class:"text-muted" %></li>
        <li><%= link_to "Support", support_path, class:"text-muted" %></li>
        <li><%= link_to "Privacy", privacy_path, class:"text-muted" %></li>
        <li><%= link_to "Terms", terms_path, class:"text-muted" %></li>
      </ul>
    </div>
  </div>
</footer>

app/views/shared/_application_msg.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 col-md-offset-1">
      <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= msg %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<nav class="container navbar navbar-expand-md navbar-light fixed-top" style="background-color: #fff;">
  <%= link_to root_path do %>
    <%= image_tag "icon-ae-wl-1024.png", width: '35', alt: "Apicius Eats Logo", class: 'navbar-brand d-inline-block align-bottom' %>
  <% end %>
  <%= link_to "ApiciusEats", root_path, class: "navbar-brand", id: "blog-header-logo" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="nav navbar-nav mr-auto">
      <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Chefs", chefs_path, class:"nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle show" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Recipes</a>
        <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
          <%= link_to "Recipes", recipes_path, class:"dropdown-item" %>
          <div class="dropdown-divider"></div>
          <%= link_to "Create a new recipe", new_recipe_path, class:"dropdown-item" %>
        </div>
      </li>
      <li class="nav-item dropdown">
        <a href="#" class="nav-link dropdown-toggle show" style="min-width: 300px;" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Ingredients</a>
        <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
          <%= link_to "Ingredient List", ingredients_path, class:"dropdown-item" %>
          <% if logged_in? && current_chef.admin? %>
            <%= link_to "Add Ingredient", new_ingredient_path, class:" dropdown-item" %>
          <% end %>
          <div class="dropdown-divider"></div>
          <div class="row w-100">
            <% Ingredient.all.each do |ingredient| %>
            <div class="col-sm-3">
              <small><%= link_to ingredient.name, ingredient_path(ingredient), class:"dropdown-item text-success" %></small>
            </div>
            <% end %>
          </div>
        </div>
      </li>
      <% else %>
        <%= nav_helper 'nav-link', 'li' %>
      <% end %>
    </ul>
    <ul class="nav navbar-nav ml-auto">
      <% if logged_in? %>
        <li class="nav-item dropdown">
          <a href="#" class="nav-link dropdown-toggle show" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><%= current_chef.chefname.titleize %>'s Profile <%= "Admin" if current_chef.admin? %> </a>
          <div class="dropdown-menu"  aria-labelledby="navbarDropdown">
            <%= link_to "View your profile", chef_path(current_chef), class:"dropdown-item" %>
            <%= link_to "Edit your profile", edit_chef_path(current_chef), class:"dropdown-item" %>
            <%= link_to "Something else here", root_path, class:"dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Log out", logout_path, method: :delete, class:"dropdown-item" %>
          </div>
        </li>
      <% else %>
        <%= link_to "Log in", login_path, class:"nav-link" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_page_title.html.erb
<h1 align="center"><%= title.titleize %></h1>
<hr />

app/views/shared/_page_title_log.html.erb
<h1 align="center"><%= title.titleize %></h1>