config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  get 'pages/home', to: 'pages#home'
  get '/about-us', to: 'pages#about'
  get '/support', to: 'pages#support'
  get '/locations', to: 'pages#locations'
  get '/privacy', to: 'pages#privacy'
  get '/terms', to: 'pages#terms'

  get '/signup', to: 'chefs#new'
  resources :chefs, except: [:new]

  resources :recipes

  resources :ingredients, except: [:destroy]

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, length: { minimum: 3, maximum: 25 }
  validates_uniqueness_of :name
  has_many :recipe_ingredients
  has_many :recipes, through: :recipe_ingredients
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  before_action :set_ingredient, only: [:show, :edit, :update]
  before_action :require_admin, except: [:show, :index]

  def index
    @ingredients = Ingredient.paginate(page: params[:page], per_page: 5)
  end

  def show
    @ingredient_recipes = @ingredient.recipes.paginate(page: params[:page], per_page: 5)
  end

  def new
    @ingredient = Ingredient.new
  end

  def create
    @ingredient = Ingredient.new(ingredient_params)
    if @ingredient.save
      flash[:success] = "Ingredient was successfully created."
      redirect_to ingredient_path(@ingredient)
    else
      render 'new'
    end
  end

  def edit

  end

  def update
    if @ingredient.update(ingredient_params)
      flash[:success] = "Ingredient was updated successfully!"
      redirect_to @ingredient
    else
      render 'edit'
    end
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:name)
  end

  def set_ingredient
    @ingredient = Ingredient.find(params[:id])
  end

  def require_admin
    if !logged_in? || (logged_in? && !current_chef.admin?)
      flash[:danger] = "Only admin users can perform that action!"
      redirect_to ingredients_path
    end
  end

end

app/views/ingredients/_form.html.erb
<%= render 'shared/application_errors', obj: @ingredient %>

<div class="row">
  <div class="col-md-12">
    <%= form_for(@ingredient, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of ingredient", autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@ingredient.new_record? ? "Add Ingredient" : "Update Ingredient",
                                                  class: "btn btn-primary btn-large btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-6 col-md-offset-4">
      [ <%= link_to "Cancel request and return to Ingredients Library", ingredients_path %> ]
    </div>
  </div>
</div>

app/views/ingredients/_ingredient.html.erb
<span class="badge"><%= link_to ingredient.name, ingredient_path(ingredient) %> &nbsp; </span>

app/views/ingredients/index.html.erb
<%= render 'shared/page_title', title: "Available Ingredients" %>

<%= will_paginate class: "text-center" %></br>
<div class="container">
  <div class="row">
    <% @ingredients.each do |ing| %>
    <ul class="listing mx-auto">
        <div class="text-center">
          <li class="chef-title"><%= link_to ing.name.capitalize, ingredient_path(ing) %></li>
          <li><small><%= pluralize(ing.recipes.count, "recipe") if ing.recipes %></small></li>
          <% if logged_in? && current_chef.admin? %>
            <li><%= link_to "Edit this ingredient", edit_ingredient_path(ing) %></li>
          <% end %>
        </div>
      </ul>
    <% end %>
  </div>
</div>
<%= will_paginate class: "text-center" %>

app/views/ingredients/new.html.erb
<div class="row" style="padding-top: 20px;">
  <div class="card w-75 border-success mx-auto" style="border-color: #66CC99">
    <div class="card-header bg-success" style="color: white;">
      <%= render 'shared/page_title_log', title: "Create a New Ingredient" %>
    </div>
    <div class="card-body text-secondary">
      <div class="card-text">
        <%= render 'form' %>
      </div>
    </div>
  </div>
</div>

app/views/ingredients/show.html.erb
<div class="container py-5 bg-light">
  <%= render 'shared/page_title', title: "#{@ingredient.name}" %>
  <div class="row">
    <div class="col-md-12">
      <% if @ingredient.recipes.count != 0 %>
        <br>
        <h4 align="center"> ~ Recipe Suggestions ~ </h4>
        <%= will_paginate @ingredient_recipes, class: "text-center" %>
        <%= render 'recipes/recipex', obj: @ingredient_recipes %>
        <%= will_paginate @ingredient_recipes, class: "text-center" %>
      <% else %>
        <br>
        <h4 align="center"> No recipes yet! </h4>
      <% end %>
    </div>
  </div>
</div>